name: On Push Backend

on:
  push:
    branches:
      - main
    paths:
      - packages/backend/**
  pull_request:
    branches:
      - main
    
# Docs: https://learn.microsoft.com/en-us/azure/azure-functions/functions-how-to-github-actions?tabs=linux%2Cjavascript&pivots=method-manual

env:
  AZURE_FUNCTIONAPP_NAME: 'gosqasbe'                    # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'packages/backend'    # set this to the path to your function app project, defaults to the repository root
  NODE_VERSION: '20.x'                                  # set this to the node version to use (e.g. '8.x', '10.x', '12.x')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4.1.7
  

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v4.0.3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm run build --if-present
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
